// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetEthereumNowData,
  GetEthereumNowErrors,
  GetEthereumNowResponses,
  GetEthereumSpecData,
  GetEthereumSpecErrors,
  GetEthereumSpecResponses,
  GetFrameData,
  GetFrameErrors,
  GetFrameResponses,
  ListMetadataData,
  ListMetadataEpochsData,
  ListMetadataEpochsErrors,
  ListMetadataEpochsResponses,
  ListMetadataErrors,
  ListMetadataLabelsData,
  ListMetadataLabelsErrors,
  ListMetadataLabelsResponses,
  ListMetadataNodesData,
  ListMetadataNodesErrors,
  ListMetadataNodesResponses,
  ListMetadataResponses,
  ListMetadataSlotsData,
  ListMetadataSlotsErrors,
  ListMetadataSlotsResponses,
} from './types.gen';
import {
  zGetEthereumNowResponse,
  zGetEthereumSpecResponse,
  zGetFrameResponse,
  zListMetadataEpochsResponse,
  zListMetadataLabelsResponse,
  zListMetadataNodesResponse,
  zListMetadataResponse,
  zListMetadataSlotsResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get the current wall-clock slot and epoch
 */
export const getEthereumNow = <ThrowOnError extends boolean = false>(
  options?: Options<GetEthereumNowData, ThrowOnError>
): RequestResult<GetEthereumNowResponses, GetEthereumNowErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetEthereumNowResponses, GetEthereumNowErrors, ThrowOnError>({
    responseValidator: async data => await zGetEthereumNowResponse.parseAsync(data),
    url: '/api/v1/ethereum/now',
    ...options,
  });

/**
 * Get the Ethereum network name and spec
 */
export const getEthereumSpec = <ThrowOnError extends boolean = false>(
  options?: Options<GetEthereumSpecData, ThrowOnError>
): RequestResult<GetEthereumSpecResponses, GetEthereumSpecErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetEthereumSpecResponses, GetEthereumSpecErrors, ThrowOnError>({
    responseValidator: async data => await zGetEthereumSpecResponse.parseAsync(data),
    url: '/api/v1/ethereum/spec',
    ...options,
  });

/**
 * Get a single fork-choice frame by ID
 */
export const getFrame = <ThrowOnError extends boolean = false>(
  options: Options<GetFrameData, ThrowOnError>
): RequestResult<GetFrameResponses, GetFrameErrors, ThrowOnError> =>
  (options.client ?? client).get<GetFrameResponses, GetFrameErrors, ThrowOnError>({
    responseValidator: async data => await zGetFrameResponse.parseAsync(data),
    url: '/api/v1/frames/{id}',
    ...options,
  });

/**
 * List fork-choice frame metadata
 */
export const listMetadata = <ThrowOnError extends boolean = false>(
  options: Options<ListMetadataData, ThrowOnError>
): RequestResult<ListMetadataResponses, ListMetadataErrors, ThrowOnError> =>
  (options.client ?? client).post<ListMetadataResponses, ListMetadataErrors, ThrowOnError>({
    responseValidator: async data => await zListMetadataResponse.parseAsync(data),
    url: '/api/v1/metadata',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List distinct nodes across stored frames
 */
export const listMetadataNodes = <ThrowOnError extends boolean = false>(
  options: Options<ListMetadataNodesData, ThrowOnError>
): RequestResult<ListMetadataNodesResponses, ListMetadataNodesErrors, ThrowOnError> =>
  (options.client ?? client).post<ListMetadataNodesResponses, ListMetadataNodesErrors, ThrowOnError>({
    responseValidator: async data => await zListMetadataNodesResponse.parseAsync(data),
    url: '/api/v1/metadata/nodes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List distinct slots across stored frames
 */
export const listMetadataSlots = <ThrowOnError extends boolean = false>(
  options: Options<ListMetadataSlotsData, ThrowOnError>
): RequestResult<ListMetadataSlotsResponses, ListMetadataSlotsErrors, ThrowOnError> =>
  (options.client ?? client).post<ListMetadataSlotsResponses, ListMetadataSlotsErrors, ThrowOnError>({
    responseValidator: async data => await zListMetadataSlotsResponse.parseAsync(data),
    url: '/api/v1/metadata/slots',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List distinct epochs across stored frames
 */
export const listMetadataEpochs = <ThrowOnError extends boolean = false>(
  options: Options<ListMetadataEpochsData, ThrowOnError>
): RequestResult<ListMetadataEpochsResponses, ListMetadataEpochsErrors, ThrowOnError> =>
  (options.client ?? client).post<ListMetadataEpochsResponses, ListMetadataEpochsErrors, ThrowOnError>({
    responseValidator: async data => await zListMetadataEpochsResponse.parseAsync(data),
    url: '/api/v1/metadata/epochs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List distinct labels across stored frames
 */
export const listMetadataLabels = <ThrowOnError extends boolean = false>(
  options: Options<ListMetadataLabelsData, ThrowOnError>
): RequestResult<ListMetadataLabelsResponses, ListMetadataLabelsErrors, ThrowOnError> =>
  (options.client ?? client).post<ListMetadataLabelsResponses, ListMetadataLabelsErrors, ThrowOnError>({
    responseValidator: async data => await zListMetadataLabelsResponse.parseAsync(data),
    url: '/api/v1/metadata/labels',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
