// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://forky.mainnet.ethpandaops.io' | 'https://forky.hoodi.ethpandaops.io' | (string & {});
};

/**
 * A beacon-chain slot number.
 */
export type Slot = number;

/**
 * A beacon-chain epoch number.
 */
export type Epoch = number;

/**
 * A beacon-chain slot number serialized as a string, following the
 * beacon-API convention used by the fork-choice dump.
 *
 */
export type SlotString = string;

/**
 * A beacon-chain epoch number serialized as a string, following the
 * beacon-API convention used by the fork-choice dump.
 *
 */
export type EpochString = string;

/**
 * A 32-byte hex-encoded root.
 */
export type Root = string;

export type Error = {
  /**
   * The HTTP status code.
   */
  code: number;
  /**
   * A human-readable error message.
   */
  message: string;
};

/**
 * Offset-based pagination cursor.
 */
export type PaginationCursor = {
  /**
   * The number of items to skip.
   */
  offset?: number;
  /**
   * The maximum number of items to return.
   */
  limit?: number;
};

export type PaginationResponse = {
  /**
   * The total number of matching items.
   */
  total: number;
};

/**
 * Filters applied to a frame query. All fields are optional.
 */
export type FrameFilter = {
  node?: string;
  before?: string;
  after?: string;
  slot?: Slot;
  epoch?: Epoch;
  labels?: Array<string>;
  consensus_client?: string;
  event_source?: string;
};

export type MetadataQuery = {
  filter?: FrameFilter;
  pagination?: PaginationCursor;
};

export type FrameMetadata = {
  /**
   * The frame ID.
   */
  id: string;
  /**
   * The node that provided the frame. For a beacon node this is the
   * configured node ID; for Xatu it is the Xatu Sentry ID.
   *
   */
  node: string;
  /**
   * When the frame was fetched.
   */
  fetched_at: string;
  wall_clock_slot: Slot;
  wall_clock_epoch: Epoch;
  labels: Array<string>;
  consensus_client: string;
  event_source: string;
};

export type Checkpoint = {
  epoch: EpochString;
  root: Root;
};

/**
 * The Gloas payload status of a fork-choice node. A Gloas block has a
 * `pending` node, which is the parent of its `empty` node (the block
 * without its execution payload) and its `full` node (the block with it).
 *
 */
export type PayloadStatus = 'pending' | 'empty' | 'full';

/**
 * A fork-choice node. Pre-Gloas, and for beacon nodes without the v2
 * fork-choice endpoint, there is one node per block. Post-Gloas a block can
 * have a `pending`, an `empty` and a `full` node, which share `slot`,
 * `block_root` and `parent_root`.
 *
 */
export type ForkChoiceNode = {
  slot: SlotString;
  block_root: Root;
  parent_root: Root;
  justified_epoch?: EpochString;
  finalized_epoch?: EpochString;
  /**
   * The node's fork-choice weight, serialized as a string.
   */
  weight: string;
  /**
   * The node's validity status.
   */
  validity: 'valid' | 'invalid' | 'optimistic' | 'unknown';
  execution_block_hash: Root;
  payload_status?: PayloadStatus;
  /**
   * The payload status of the parent fork-choice node: for a `pending`
   * node, whether the block was built on its parent block's `empty` or
   * `full` payload; for `empty` and `full` nodes, `pending`. Absent if
   * unknown.
   *
   */
  parent_payload_status?: PayloadStatus;
  /**
   * Number of Payload Timeliness Committee positions with a recorded vote.
   */
  payload_attester_count?: string;
  /**
   * Number of PTC positions voting that the payload was received on time.
   */
  payload_availability_yes_count?: string;
  /**
   * Number of PTC positions voting that the blob data is available.
   */
  payload_data_availability_yes_count?: string;
  extra_data?: {
    [key: string]: unknown;
  };
};

/**
 * A beacon node's fork-choice dump.
 */
export type ForkChoice = {
  justified_checkpoint: Checkpoint;
  finalized_checkpoint: Checkpoint;
  fork_choice_nodes: Array<ForkChoiceNode>;
  /**
   * Client-specific values of the fork-choice store, such as the
   * unrealized justified checkpoint.
   *
   */
  extra_data?: {
    [key: string]: unknown;
  };
};

export type Frame = {
  data: ForkChoice;
  metadata: FrameMetadata;
};

export type EthereumNow = {
  slot: Slot;
  epoch: Epoch;
};

export type EthereumSpec = {
  seconds_per_slot: number;
  slots_per_epoch: number;
  genesis_time: string;
};

export type EthereumSpecResult = {
  network_name: string;
  spec: EthereumSpec;
};

/**
 * Filter and pagination for a metadata query.
 */
export type MetadataQuery2 = MetadataQuery;

export type GetEthereumNowData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/ethereum/now';
};

export type GetEthereumNowErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type GetEthereumNowError = GetEthereumNowErrors[keyof GetEthereumNowErrors];

export type GetEthereumNowResponses = {
  /**
   * The current wall-clock slot and epoch.
   */
  200: {
    data: EthereumNow;
  };
};

export type GetEthereumNowResponse = GetEthereumNowResponses[keyof GetEthereumNowResponses];

export type GetEthereumSpecData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/ethereum/spec';
};

export type GetEthereumSpecErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type GetEthereumSpecError = GetEthereumSpecErrors[keyof GetEthereumSpecErrors];

export type GetEthereumSpecResponses = {
  /**
   * The configured network name and spec.
   */
  200: {
    data: EthereumSpecResult;
  };
};

export type GetEthereumSpecResponse = GetEthereumSpecResponses[keyof GetEthereumSpecResponses];

export type GetFrameData = {
  body?: never;
  path: {
    /**
     * The frame ID.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/frames/{id}';
};

export type GetFrameErrors = {
  /**
   * The requested resource was not found.
   */
  404: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type GetFrameError = GetFrameErrors[keyof GetFrameErrors];

export type GetFrameResponses = {
  /**
   * The requested fork-choice frame.
   */
  200: {
    data: {
      frame: Frame;
    };
  };
};

export type GetFrameResponse = GetFrameResponses[keyof GetFrameResponses];

export type ListMetadataData = {
  /**
   * Filter and pagination for a metadata query.
   */
  body: MetadataQuery2;
  path?: never;
  query?: never;
  url: '/api/v1/metadata';
};

export type ListMetadataErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type ListMetadataError = ListMetadataErrors[keyof ListMetadataErrors];

export type ListMetadataResponses = {
  /**
   * A page of frame metadata.
   */
  200: {
    data: {
      frames: Array<FrameMetadata>;
      pagination: PaginationResponse;
    };
  };
};

export type ListMetadataResponse = ListMetadataResponses[keyof ListMetadataResponses];

export type ListMetadataNodesData = {
  /**
   * Filter and pagination for a metadata query.
   */
  body: MetadataQuery2;
  path?: never;
  query?: never;
  url: '/api/v1/metadata/nodes';
};

export type ListMetadataNodesErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type ListMetadataNodesError = ListMetadataNodesErrors[keyof ListMetadataNodesErrors];

export type ListMetadataNodesResponses = {
  /**
   * A page of distinct node names.
   */
  200: {
    data: {
      nodes: Array<string>;
      pagination: PaginationResponse;
    };
  };
};

export type ListMetadataNodesResponse = ListMetadataNodesResponses[keyof ListMetadataNodesResponses];

export type ListMetadataSlotsData = {
  /**
   * Filter and pagination for a metadata query.
   */
  body: MetadataQuery2;
  path?: never;
  query?: never;
  url: '/api/v1/metadata/slots';
};

export type ListMetadataSlotsErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type ListMetadataSlotsError = ListMetadataSlotsErrors[keyof ListMetadataSlotsErrors];

export type ListMetadataSlotsResponses = {
  /**
   * A page of distinct slots.
   */
  200: {
    data: {
      slots: Array<Slot>;
      pagination: PaginationResponse;
    };
  };
};

export type ListMetadataSlotsResponse = ListMetadataSlotsResponses[keyof ListMetadataSlotsResponses];

export type ListMetadataEpochsData = {
  /**
   * Filter and pagination for a metadata query.
   */
  body: MetadataQuery2;
  path?: never;
  query?: never;
  url: '/api/v1/metadata/epochs';
};

export type ListMetadataEpochsErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type ListMetadataEpochsError = ListMetadataEpochsErrors[keyof ListMetadataEpochsErrors];

export type ListMetadataEpochsResponses = {
  /**
   * A page of distinct epochs.
   */
  200: {
    data: {
      epochs: Array<Epoch>;
      pagination: PaginationResponse;
    };
  };
};

export type ListMetadataEpochsResponse = ListMetadataEpochsResponses[keyof ListMetadataEpochsResponses];

export type ListMetadataLabelsData = {
  /**
   * Filter and pagination for a metadata query.
   */
  body: MetadataQuery2;
  path?: never;
  query?: never;
  url: '/api/v1/metadata/labels';
};

export type ListMetadataLabelsErrors = {
  /**
   * The request was malformed.
   */
  400: Error;
  /**
   * An unexpected error occurred.
   */
  default: Error;
};

export type ListMetadataLabelsError = ListMetadataLabelsErrors[keyof ListMetadataLabelsErrors];

export type ListMetadataLabelsResponses = {
  /**
   * A page of distinct labels.
   */
  200: {
    data: {
      labels: Array<string>;
      pagination: PaginationResponse;
    };
  };
};

export type ListMetadataLabelsResponse = ListMetadataLabelsResponses[keyof ListMetadataLabelsResponses];
