// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * A beacon-chain slot number.
 */
export const zSlot = z.coerce
  .bigint()
  .check(
    z.gte(BigInt(0)),
    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
  );

/**
 * A beacon-chain epoch number.
 */
export const zEpoch = z.coerce
  .bigint()
  .check(
    z.gte(BigInt(0)),
    z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
  );

/**
 * A beacon-chain slot number serialized as a string, following the
 * beacon-API convention used by the fork-choice dump.
 *
 */
export const zSlotString = z.string();

/**
 * A beacon-chain epoch number serialized as a string, following the
 * beacon-API convention used by the fork-choice dump.
 *
 */
export const zEpochString = z.string();

/**
 * A 32-byte hex-encoded root.
 */
export const zRoot = z.string();

export const zError = z.object({
  code: z.int(),
  message: z.string(),
});

/**
 * Offset-based pagination cursor.
 */
export const zPaginationCursor = z.object({
  offset: z._default(z.optional(z.int()), 0),
  limit: z._default(z.optional(z.int()), 1000),
});

export const zPaginationResponse = z.object({
  total: z.coerce
    .bigint()
    .check(
      z.minimum(BigInt('-9223372036854775808'), {
        error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
      }),
      z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ),
});

/**
 * Filters applied to a frame query. All fields are optional.
 */
export const zFrameFilter = z.object({
  node: z.optional(z.string()),
  before: z.optional(z.iso.datetime()),
  after: z.optional(z.iso.datetime()),
  slot: z.optional(zSlot),
  epoch: z.optional(zEpoch),
  labels: z.optional(z.array(z.string())),
  consensus_client: z.optional(z.string()),
  event_source: z.optional(z.string()),
});

export const zMetadataQuery = z.object({
  filter: z.optional(zFrameFilter),
  pagination: z.optional(zPaginationCursor),
});

export const zFrameMetadata = z.object({
  id: z.string(),
  node: z.string(),
  fetched_at: z.iso.datetime(),
  wall_clock_slot: zSlot,
  wall_clock_epoch: zEpoch,
  labels: z.array(z.string()),
  consensus_client: z.string(),
  event_source: z.string(),
});

export const zCheckpoint = z.object({
  epoch: zEpochString,
  root: zRoot,
});

export const zForkChoiceNode = z.object({
  slot: zSlotString,
  block_root: zRoot,
  parent_root: zRoot,
  justified_epoch: zEpochString,
  finalized_epoch: zEpochString,
  weight: z.string(),
  validity: z.enum(['valid', 'invalid', 'optimistic', 'unknown']),
  execution_block_hash: zRoot,
  extra_data: z.optional(z.record(z.string(), z.unknown())),
});

/**
 * A beacon node's fork-choice dump.
 */
export const zForkChoice = z.object({
  justified_checkpoint: zCheckpoint,
  finalized_checkpoint: zCheckpoint,
  fork_choice_nodes: z.array(zForkChoiceNode),
});

export const zFrame = z.object({
  data: zForkChoice,
  metadata: zFrameMetadata,
});

export const zEthereumNow = z.object({
  slot: zSlot,
  epoch: zEpoch,
});

export const zEthereumSpec = z.object({
  seconds_per_slot: z.coerce
    .bigint()
    .check(
      z.minimum(BigInt('-9223372036854775808'), {
        error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
      }),
      z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ),
  slots_per_epoch: z.coerce
    .bigint()
    .check(
      z.minimum(BigInt('-9223372036854775808'), {
        error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
      }),
      z.maximum(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ),
  genesis_time: z.iso.datetime(),
});

export const zEthereumSpecResult = z.object({
  network_name: z.string(),
  spec: zEthereumSpec,
});

/**
 * Filter and pagination for a metadata query.
 */
export const zMetadataQuery2 = zMetadataQuery;

/**
 * The current wall-clock slot and epoch.
 */
export const zGetEthereumNowResponse = z.object({
  data: zEthereumNow,
});

/**
 * The configured network name and spec.
 */
export const zGetEthereumSpecResponse = z.object({
  data: zEthereumSpecResult,
});

export const zGetFramePath = z.object({
  id: z.string(),
});

/**
 * The requested fork-choice frame.
 */
export const zGetFrameResponse = z.object({
  data: z.object({
    frame: zFrame,
  }),
});

/**
 * Filter and pagination for a metadata query.
 */
export const zListMetadataBody = zMetadataQuery2;

/**
 * A page of frame metadata.
 */
export const zListMetadataResponse = z.object({
  data: z.object({
    frames: z.array(zFrameMetadata),
    pagination: zPaginationResponse,
  }),
});

/**
 * Filter and pagination for a metadata query.
 */
export const zListMetadataNodesBody = zMetadataQuery2;

/**
 * A page of distinct node names.
 */
export const zListMetadataNodesResponse = z.object({
  data: z.object({
    nodes: z.array(z.string()),
    pagination: zPaginationResponse,
  }),
});

/**
 * Filter and pagination for a metadata query.
 */
export const zListMetadataSlotsBody = zMetadataQuery2;

/**
 * A page of distinct slots.
 */
export const zListMetadataSlotsResponse = z.object({
  data: z.object({
    slots: z.array(zSlot),
    pagination: zPaginationResponse,
  }),
});

/**
 * Filter and pagination for a metadata query.
 */
export const zListMetadataEpochsBody = zMetadataQuery2;

/**
 * A page of distinct epochs.
 */
export const zListMetadataEpochsResponse = z.object({
  data: z.object({
    epochs: z.array(zEpoch),
    pagination: zPaginationResponse,
  }),
});

/**
 * Filter and pagination for a metadata query.
 */
export const zListMetadataLabelsBody = zMetadataQuery2;

/**
 * A page of distinct labels.
 */
export const zListMetadataLabelsResponse = z.object({
  data: z.object({
    labels: z.array(z.string()),
    pagination: zPaginationResponse,
  }),
});
