// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  getEthereumNow,
  getEthereumSpec,
  getFrame,
  listMetadata,
  listMetadataEpochs,
  listMetadataLabels,
  listMetadataNodes,
  listMetadataSlots,
  type Options,
} from '../sdk.gen';
import type {
  GetEthereumNowData,
  GetEthereumNowError,
  GetEthereumNowResponse,
  GetEthereumSpecData,
  GetEthereumSpecError,
  GetEthereumSpecResponse,
  GetFrameData,
  GetFrameError,
  GetFrameResponse,
  ListMetadataData,
  ListMetadataEpochsData,
  ListMetadataEpochsError,
  ListMetadataEpochsResponse,
  ListMetadataError,
  ListMetadataLabelsData,
  ListMetadataLabelsError,
  ListMetadataLabelsResponse,
  ListMetadataNodesData,
  ListMetadataNodesError,
  ListMetadataNodesResponse,
  ListMetadataResponse,
  ListMetadataSlotsData,
  ListMetadataSlotsError,
  ListMetadataSlotsResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getEthereumNowQueryKey = (options?: Options<GetEthereumNowData>) =>
  createQueryKey('getEthereumNow', options);

/**
 * Get the current wall-clock slot and epoch
 */
export const getEthereumNowOptions = (options?: Options<GetEthereumNowData>) =>
  queryOptions<
    GetEthereumNowResponse,
    GetEthereumNowError,
    GetEthereumNowResponse,
    ReturnType<typeof getEthereumNowQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEthereumNow({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEthereumNowQueryKey(options),
  });

export const getEthereumSpecQueryKey = (options?: Options<GetEthereumSpecData>) =>
  createQueryKey('getEthereumSpec', options);

/**
 * Get the Ethereum network name and spec
 */
export const getEthereumSpecOptions = (options?: Options<GetEthereumSpecData>) =>
  queryOptions<
    GetEthereumSpecResponse,
    GetEthereumSpecError,
    GetEthereumSpecResponse,
    ReturnType<typeof getEthereumSpecQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEthereumSpec({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEthereumSpecQueryKey(options),
  });

export const getFrameQueryKey = (options: Options<GetFrameData>) => createQueryKey('getFrame', options);

/**
 * Get a single fork-choice frame by ID
 */
export const getFrameOptions = (options: Options<GetFrameData>) =>
  queryOptions<GetFrameResponse, GetFrameError, GetFrameResponse, ReturnType<typeof getFrameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFrame({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFrameQueryKey(options),
  });

/**
 * List fork-choice frame metadata
 */
export const listMetadataMutation = (
  options?: Partial<Options<ListMetadataData>>
): UseMutationOptions<ListMetadataResponse, ListMetadataError, Options<ListMetadataData>> => {
  const mutationOptions: UseMutationOptions<ListMetadataResponse, ListMetadataError, Options<ListMetadataData>> = {
    mutationFn: async fnOptions => {
      const { data } = await listMetadata({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * List distinct nodes across stored frames
 */
export const listMetadataNodesMutation = (
  options?: Partial<Options<ListMetadataNodesData>>
): UseMutationOptions<ListMetadataNodesResponse, ListMetadataNodesError, Options<ListMetadataNodesData>> => {
  const mutationOptions: UseMutationOptions<
    ListMetadataNodesResponse,
    ListMetadataNodesError,
    Options<ListMetadataNodesData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await listMetadataNodes({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * List distinct slots across stored frames
 */
export const listMetadataSlotsMutation = (
  options?: Partial<Options<ListMetadataSlotsData>>
): UseMutationOptions<ListMetadataSlotsResponse, ListMetadataSlotsError, Options<ListMetadataSlotsData>> => {
  const mutationOptions: UseMutationOptions<
    ListMetadataSlotsResponse,
    ListMetadataSlotsError,
    Options<ListMetadataSlotsData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await listMetadataSlots({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * List distinct epochs across stored frames
 */
export const listMetadataEpochsMutation = (
  options?: Partial<Options<ListMetadataEpochsData>>
): UseMutationOptions<ListMetadataEpochsResponse, ListMetadataEpochsError, Options<ListMetadataEpochsData>> => {
  const mutationOptions: UseMutationOptions<
    ListMetadataEpochsResponse,
    ListMetadataEpochsError,
    Options<ListMetadataEpochsData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await listMetadataEpochs({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * List distinct labels across stored frames
 */
export const listMetadataLabelsMutation = (
  options?: Partial<Options<ListMetadataLabelsData>>
): UseMutationOptions<ListMetadataLabelsResponse, ListMetadataLabelsError, Options<ListMetadataLabelsData>> => {
  const mutationOptions: UseMutationOptions<
    ListMetadataLabelsResponse,
    ListMetadataLabelsError,
    Options<ListMetadataLabelsData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await listMetadataLabels({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
