// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	GetEthereumNowOperation     OperationName = "GetEthereumNow"
	GetEthereumSpecOperation    OperationName = "GetEthereumSpec"
	GetFrameOperation           OperationName = "GetFrame"
	ListMetadataOperation       OperationName = "ListMetadata"
	ListMetadataEpochsOperation OperationName = "ListMetadataEpochs"
	ListMetadataLabelsOperation OperationName = "ListMetadataLabels"
	ListMetadataNodesOperation  OperationName = "ListMetadataNodes"
	ListMetadataSlotsOperation  OperationName = "ListMetadataSlots"
)
