// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *UnexpectedErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Checkpoint
type Checkpoint struct {
	Epoch EpochString `json:"epoch"`
	Root  Root        `json:"root"`
}

// GetEpoch returns the value of Epoch.
func (s *Checkpoint) GetEpoch() EpochString {
	return s.Epoch
}

// GetRoot returns the value of Root.
func (s *Checkpoint) GetRoot() Root {
	return s.Root
}

// SetEpoch sets the value of Epoch.
func (s *Checkpoint) SetEpoch(val EpochString) {
	s.Epoch = val
}

// SetRoot sets the value of Root.
func (s *Checkpoint) SetRoot(val Root) {
	s.Root = val
}

type Epoch int64

type EpochString string

// Ref: #/components/schemas/Error
type Error struct {
	// The HTTP status code.
	Code int `json:"code"`
	// A human-readable error message.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getEthereumNowRes()     {}
func (*Error) getEthereumSpecRes()    {}
func (*Error) getFrameRes()           {}
func (*Error) listMetadataEpochsRes() {}
func (*Error) listMetadataLabelsRes() {}
func (*Error) listMetadataNodesRes()  {}
func (*Error) listMetadataRes()       {}
func (*Error) listMetadataSlotsRes()  {}

// Ref: #/components/schemas/EthereumNow
type EthereumNow struct {
	Slot  Slot  `json:"slot"`
	Epoch Epoch `json:"epoch"`
}

// GetSlot returns the value of Slot.
func (s *EthereumNow) GetSlot() Slot {
	return s.Slot
}

// GetEpoch returns the value of Epoch.
func (s *EthereumNow) GetEpoch() Epoch {
	return s.Epoch
}

// SetSlot sets the value of Slot.
func (s *EthereumNow) SetSlot(val Slot) {
	s.Slot = val
}

// SetEpoch sets the value of Epoch.
func (s *EthereumNow) SetEpoch(val Epoch) {
	s.Epoch = val
}

// Ref: #/components/schemas/EthereumSpec
type EthereumSpec struct {
	SecondsPerSlot int64     `json:"seconds_per_slot"`
	SlotsPerEpoch  int64     `json:"slots_per_epoch"`
	GenesisTime    time.Time `json:"genesis_time"`
}

// GetSecondsPerSlot returns the value of SecondsPerSlot.
func (s *EthereumSpec) GetSecondsPerSlot() int64 {
	return s.SecondsPerSlot
}

// GetSlotsPerEpoch returns the value of SlotsPerEpoch.
func (s *EthereumSpec) GetSlotsPerEpoch() int64 {
	return s.SlotsPerEpoch
}

// GetGenesisTime returns the value of GenesisTime.
func (s *EthereumSpec) GetGenesisTime() time.Time {
	return s.GenesisTime
}

// SetSecondsPerSlot sets the value of SecondsPerSlot.
func (s *EthereumSpec) SetSecondsPerSlot(val int64) {
	s.SecondsPerSlot = val
}

// SetSlotsPerEpoch sets the value of SlotsPerEpoch.
func (s *EthereumSpec) SetSlotsPerEpoch(val int64) {
	s.SlotsPerEpoch = val
}

// SetGenesisTime sets the value of GenesisTime.
func (s *EthereumSpec) SetGenesisTime(val time.Time) {
	s.GenesisTime = val
}

// Ref: #/components/schemas/EthereumSpecResult
type EthereumSpecResult struct {
	NetworkName string       `json:"network_name"`
	Spec        EthereumSpec `json:"spec"`
}

// GetNetworkName returns the value of NetworkName.
func (s *EthereumSpecResult) GetNetworkName() string {
	return s.NetworkName
}

// GetSpec returns the value of Spec.
func (s *EthereumSpecResult) GetSpec() EthereumSpec {
	return s.Spec
}

// SetNetworkName sets the value of NetworkName.
func (s *EthereumSpecResult) SetNetworkName(val string) {
	s.NetworkName = val
}

// SetSpec sets the value of Spec.
func (s *EthereumSpecResult) SetSpec(val EthereumSpec) {
	s.Spec = val
}

// A beacon node's fork-choice dump.
// Ref: #/components/schemas/ForkChoice
type ForkChoice struct {
	JustifiedCheckpoint Checkpoint       `json:"justified_checkpoint"`
	FinalizedCheckpoint Checkpoint       `json:"finalized_checkpoint"`
	ForkChoiceNodes     []ForkChoiceNode `json:"fork_choice_nodes"`
	// Client-specific values of the fork-choice store, such as the
	// unrealized justified checkpoint.
	ExtraData OptForkChoiceExtraData `json:"extra_data"`
}

// GetJustifiedCheckpoint returns the value of JustifiedCheckpoint.
func (s *ForkChoice) GetJustifiedCheckpoint() Checkpoint {
	return s.JustifiedCheckpoint
}

// GetFinalizedCheckpoint returns the value of FinalizedCheckpoint.
func (s *ForkChoice) GetFinalizedCheckpoint() Checkpoint {
	return s.FinalizedCheckpoint
}

// GetForkChoiceNodes returns the value of ForkChoiceNodes.
func (s *ForkChoice) GetForkChoiceNodes() []ForkChoiceNode {
	return s.ForkChoiceNodes
}

// GetExtraData returns the value of ExtraData.
func (s *ForkChoice) GetExtraData() OptForkChoiceExtraData {
	return s.ExtraData
}

// SetJustifiedCheckpoint sets the value of JustifiedCheckpoint.
func (s *ForkChoice) SetJustifiedCheckpoint(val Checkpoint) {
	s.JustifiedCheckpoint = val
}

// SetFinalizedCheckpoint sets the value of FinalizedCheckpoint.
func (s *ForkChoice) SetFinalizedCheckpoint(val Checkpoint) {
	s.FinalizedCheckpoint = val
}

// SetForkChoiceNodes sets the value of ForkChoiceNodes.
func (s *ForkChoice) SetForkChoiceNodes(val []ForkChoiceNode) {
	s.ForkChoiceNodes = val
}

// SetExtraData sets the value of ExtraData.
func (s *ForkChoice) SetExtraData(val OptForkChoiceExtraData) {
	s.ExtraData = val
}

// Client-specific values of the fork-choice store, such as the
// unrealized justified checkpoint.
type ForkChoiceExtraData map[string]jx.Raw

func (s *ForkChoiceExtraData) init() ForkChoiceExtraData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// A fork-choice node. Pre-Gloas, and for beacon nodes without the v2
// fork-choice endpoint, there is one node per block. Post-Gloas a block can
// have a `pending`, an `empty` and a `full` node, which share `slot`,
// `block_root` and `parent_root`.
// Ref: #/components/schemas/ForkChoiceNode
type ForkChoiceNode struct {
	Slot           SlotString     `json:"slot"`
	BlockRoot      Root           `json:"block_root"`
	ParentRoot     Root           `json:"parent_root"`
	JustifiedEpoch OptEpochString `json:"justified_epoch"`
	FinalizedEpoch OptEpochString `json:"finalized_epoch"`
	// The node's fork-choice weight, serialized as a string.
	Weight string `json:"weight"`
	// The node's validity status.
	Validity           ForkChoiceNodeValidity `json:"validity"`
	ExecutionBlockHash Root                   `json:"execution_block_hash"`
	PayloadStatus      OptPayloadStatus       `json:"payload_status"`
	// The payload status of the parent fork-choice node: for a `pending`
	// node, whether the block was built on its parent block's `empty` or
	// `full` payload; for `empty` and `full` nodes, `pending`. Absent if
	// unknown.
	ParentPayloadStatus OptPayloadStatus `json:"parent_payload_status"`
	// Number of Payload Timeliness Committee positions with a recorded vote.
	PayloadAttesterCount OptString `json:"payload_attester_count"`
	// Number of PTC positions voting that the payload was received on time.
	PayloadAvailabilityYesCount OptString `json:"payload_availability_yes_count"`
	// Number of PTC positions voting that the blob data is available.
	PayloadDataAvailabilityYesCount OptString                  `json:"payload_data_availability_yes_count"`
	ExtraData                       OptForkChoiceNodeExtraData `json:"extra_data"`
}

// GetSlot returns the value of Slot.
func (s *ForkChoiceNode) GetSlot() SlotString {
	return s.Slot
}

// GetBlockRoot returns the value of BlockRoot.
func (s *ForkChoiceNode) GetBlockRoot() Root {
	return s.BlockRoot
}

// GetParentRoot returns the value of ParentRoot.
func (s *ForkChoiceNode) GetParentRoot() Root {
	return s.ParentRoot
}

// GetJustifiedEpoch returns the value of JustifiedEpoch.
func (s *ForkChoiceNode) GetJustifiedEpoch() OptEpochString {
	return s.JustifiedEpoch
}

// GetFinalizedEpoch returns the value of FinalizedEpoch.
func (s *ForkChoiceNode) GetFinalizedEpoch() OptEpochString {
	return s.FinalizedEpoch
}

// GetWeight returns the value of Weight.
func (s *ForkChoiceNode) GetWeight() string {
	return s.Weight
}

// GetValidity returns the value of Validity.
func (s *ForkChoiceNode) GetValidity() ForkChoiceNodeValidity {
	return s.Validity
}

// GetExecutionBlockHash returns the value of ExecutionBlockHash.
func (s *ForkChoiceNode) GetExecutionBlockHash() Root {
	return s.ExecutionBlockHash
}

// GetPayloadStatus returns the value of PayloadStatus.
func (s *ForkChoiceNode) GetPayloadStatus() OptPayloadStatus {
	return s.PayloadStatus
}

// GetParentPayloadStatus returns the value of ParentPayloadStatus.
func (s *ForkChoiceNode) GetParentPayloadStatus() OptPayloadStatus {
	return s.ParentPayloadStatus
}

// GetPayloadAttesterCount returns the value of PayloadAttesterCount.
func (s *ForkChoiceNode) GetPayloadAttesterCount() OptString {
	return s.PayloadAttesterCount
}

// GetPayloadAvailabilityYesCount returns the value of PayloadAvailabilityYesCount.
func (s *ForkChoiceNode) GetPayloadAvailabilityYesCount() OptString {
	return s.PayloadAvailabilityYesCount
}

// GetPayloadDataAvailabilityYesCount returns the value of PayloadDataAvailabilityYesCount.
func (s *ForkChoiceNode) GetPayloadDataAvailabilityYesCount() OptString {
	return s.PayloadDataAvailabilityYesCount
}

// GetExtraData returns the value of ExtraData.
func (s *ForkChoiceNode) GetExtraData() OptForkChoiceNodeExtraData {
	return s.ExtraData
}

// SetSlot sets the value of Slot.
func (s *ForkChoiceNode) SetSlot(val SlotString) {
	s.Slot = val
}

// SetBlockRoot sets the value of BlockRoot.
func (s *ForkChoiceNode) SetBlockRoot(val Root) {
	s.BlockRoot = val
}

// SetParentRoot sets the value of ParentRoot.
func (s *ForkChoiceNode) SetParentRoot(val Root) {
	s.ParentRoot = val
}

// SetJustifiedEpoch sets the value of JustifiedEpoch.
func (s *ForkChoiceNode) SetJustifiedEpoch(val OptEpochString) {
	s.JustifiedEpoch = val
}

// SetFinalizedEpoch sets the value of FinalizedEpoch.
func (s *ForkChoiceNode) SetFinalizedEpoch(val OptEpochString) {
	s.FinalizedEpoch = val
}

// SetWeight sets the value of Weight.
func (s *ForkChoiceNode) SetWeight(val string) {
	s.Weight = val
}

// SetValidity sets the value of Validity.
func (s *ForkChoiceNode) SetValidity(val ForkChoiceNodeValidity) {
	s.Validity = val
}

// SetExecutionBlockHash sets the value of ExecutionBlockHash.
func (s *ForkChoiceNode) SetExecutionBlockHash(val Root) {
	s.ExecutionBlockHash = val
}

// SetPayloadStatus sets the value of PayloadStatus.
func (s *ForkChoiceNode) SetPayloadStatus(val OptPayloadStatus) {
	s.PayloadStatus = val
}

// SetParentPayloadStatus sets the value of ParentPayloadStatus.
func (s *ForkChoiceNode) SetParentPayloadStatus(val OptPayloadStatus) {
	s.ParentPayloadStatus = val
}

// SetPayloadAttesterCount sets the value of PayloadAttesterCount.
func (s *ForkChoiceNode) SetPayloadAttesterCount(val OptString) {
	s.PayloadAttesterCount = val
}

// SetPayloadAvailabilityYesCount sets the value of PayloadAvailabilityYesCount.
func (s *ForkChoiceNode) SetPayloadAvailabilityYesCount(val OptString) {
	s.PayloadAvailabilityYesCount = val
}

// SetPayloadDataAvailabilityYesCount sets the value of PayloadDataAvailabilityYesCount.
func (s *ForkChoiceNode) SetPayloadDataAvailabilityYesCount(val OptString) {
	s.PayloadDataAvailabilityYesCount = val
}

// SetExtraData sets the value of ExtraData.
func (s *ForkChoiceNode) SetExtraData(val OptForkChoiceNodeExtraData) {
	s.ExtraData = val
}

type ForkChoiceNodeExtraData map[string]jx.Raw

func (s *ForkChoiceNodeExtraData) init() ForkChoiceNodeExtraData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// The node's validity status.
type ForkChoiceNodeValidity string

const (
	ForkChoiceNodeValidityValid      ForkChoiceNodeValidity = "valid"
	ForkChoiceNodeValidityInvalid    ForkChoiceNodeValidity = "invalid"
	ForkChoiceNodeValidityOptimistic ForkChoiceNodeValidity = "optimistic"
	ForkChoiceNodeValidityUnknown    ForkChoiceNodeValidity = "unknown"
)

// AllValues returns all ForkChoiceNodeValidity values.
func (ForkChoiceNodeValidity) AllValues() []ForkChoiceNodeValidity {
	return []ForkChoiceNodeValidity{
		ForkChoiceNodeValidityValid,
		ForkChoiceNodeValidityInvalid,
		ForkChoiceNodeValidityOptimistic,
		ForkChoiceNodeValidityUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ForkChoiceNodeValidity) MarshalText() ([]byte, error) {
	switch s {
	case ForkChoiceNodeValidityValid:
		return []byte(s), nil
	case ForkChoiceNodeValidityInvalid:
		return []byte(s), nil
	case ForkChoiceNodeValidityOptimistic:
		return []byte(s), nil
	case ForkChoiceNodeValidityUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ForkChoiceNodeValidity) UnmarshalText(data []byte) error {
	switch ForkChoiceNodeValidity(data) {
	case ForkChoiceNodeValidityValid:
		*s = ForkChoiceNodeValidityValid
		return nil
	case ForkChoiceNodeValidityInvalid:
		*s = ForkChoiceNodeValidityInvalid
		return nil
	case ForkChoiceNodeValidityOptimistic:
		*s = ForkChoiceNodeValidityOptimistic
		return nil
	case ForkChoiceNodeValidityUnknown:
		*s = ForkChoiceNodeValidityUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Frame
type Frame struct {
	Data     ForkChoice    `json:"data"`
	Metadata FrameMetadata `json:"metadata"`
}

// GetData returns the value of Data.
func (s *Frame) GetData() ForkChoice {
	return s.Data
}

// GetMetadata returns the value of Metadata.
func (s *Frame) GetMetadata() FrameMetadata {
	return s.Metadata
}

// SetData sets the value of Data.
func (s *Frame) SetData(val ForkChoice) {
	s.Data = val
}

// SetMetadata sets the value of Metadata.
func (s *Frame) SetMetadata(val FrameMetadata) {
	s.Metadata = val
}

// Filters applied to a frame query. All fields are optional.
// Ref: #/components/schemas/FrameFilter
type FrameFilter struct {
	Node            OptString   `json:"node"`
	Before          OptDateTime `json:"before"`
	After           OptDateTime `json:"after"`
	Slot            OptSlot     `json:"slot"`
	Epoch           OptEpoch    `json:"epoch"`
	Labels          []string    `json:"labels"`
	ConsensusClient OptString   `json:"consensus_client"`
	EventSource     OptString   `json:"event_source"`
}

// GetNode returns the value of Node.
func (s *FrameFilter) GetNode() OptString {
	return s.Node
}

// GetBefore returns the value of Before.
func (s *FrameFilter) GetBefore() OptDateTime {
	return s.Before
}

// GetAfter returns the value of After.
func (s *FrameFilter) GetAfter() OptDateTime {
	return s.After
}

// GetSlot returns the value of Slot.
func (s *FrameFilter) GetSlot() OptSlot {
	return s.Slot
}

// GetEpoch returns the value of Epoch.
func (s *FrameFilter) GetEpoch() OptEpoch {
	return s.Epoch
}

// GetLabels returns the value of Labels.
func (s *FrameFilter) GetLabels() []string {
	return s.Labels
}

// GetConsensusClient returns the value of ConsensusClient.
func (s *FrameFilter) GetConsensusClient() OptString {
	return s.ConsensusClient
}

// GetEventSource returns the value of EventSource.
func (s *FrameFilter) GetEventSource() OptString {
	return s.EventSource
}

// SetNode sets the value of Node.
func (s *FrameFilter) SetNode(val OptString) {
	s.Node = val
}

// SetBefore sets the value of Before.
func (s *FrameFilter) SetBefore(val OptDateTime) {
	s.Before = val
}

// SetAfter sets the value of After.
func (s *FrameFilter) SetAfter(val OptDateTime) {
	s.After = val
}

// SetSlot sets the value of Slot.
func (s *FrameFilter) SetSlot(val OptSlot) {
	s.Slot = val
}

// SetEpoch sets the value of Epoch.
func (s *FrameFilter) SetEpoch(val OptEpoch) {
	s.Epoch = val
}

// SetLabels sets the value of Labels.
func (s *FrameFilter) SetLabels(val []string) {
	s.Labels = val
}

// SetConsensusClient sets the value of ConsensusClient.
func (s *FrameFilter) SetConsensusClient(val OptString) {
	s.ConsensusClient = val
}

// SetEventSource sets the value of EventSource.
func (s *FrameFilter) SetEventSource(val OptString) {
	s.EventSource = val
}

// Ref: #/components/schemas/FrameMetadata
type FrameMetadata struct {
	// The frame ID.
	ID string `json:"id"`
	// The node that provided the frame. For a beacon node this is the
	// configured node ID; for Xatu it is the Xatu Sentry ID.
	Node string `json:"node"`
	// When the frame was fetched.
	FetchedAt       time.Time `json:"fetched_at"`
	WallClockSlot   Slot      `json:"wall_clock_slot"`
	WallClockEpoch  Epoch     `json:"wall_clock_epoch"`
	Labels          []string  `json:"labels"`
	ConsensusClient string    `json:"consensus_client"`
	EventSource     string    `json:"event_source"`
}

// GetID returns the value of ID.
func (s *FrameMetadata) GetID() string {
	return s.ID
}

// GetNode returns the value of Node.
func (s *FrameMetadata) GetNode() string {
	return s.Node
}

// GetFetchedAt returns the value of FetchedAt.
func (s *FrameMetadata) GetFetchedAt() time.Time {
	return s.FetchedAt
}

// GetWallClockSlot returns the value of WallClockSlot.
func (s *FrameMetadata) GetWallClockSlot() Slot {
	return s.WallClockSlot
}

// GetWallClockEpoch returns the value of WallClockEpoch.
func (s *FrameMetadata) GetWallClockEpoch() Epoch {
	return s.WallClockEpoch
}

// GetLabels returns the value of Labels.
func (s *FrameMetadata) GetLabels() []string {
	return s.Labels
}

// GetConsensusClient returns the value of ConsensusClient.
func (s *FrameMetadata) GetConsensusClient() string {
	return s.ConsensusClient
}

// GetEventSource returns the value of EventSource.
func (s *FrameMetadata) GetEventSource() string {
	return s.EventSource
}

// SetID sets the value of ID.
func (s *FrameMetadata) SetID(val string) {
	s.ID = val
}

// SetNode sets the value of Node.
func (s *FrameMetadata) SetNode(val string) {
	s.Node = val
}

// SetFetchedAt sets the value of FetchedAt.
func (s *FrameMetadata) SetFetchedAt(val time.Time) {
	s.FetchedAt = val
}

// SetWallClockSlot sets the value of WallClockSlot.
func (s *FrameMetadata) SetWallClockSlot(val Slot) {
	s.WallClockSlot = val
}

// SetWallClockEpoch sets the value of WallClockEpoch.
func (s *FrameMetadata) SetWallClockEpoch(val Epoch) {
	s.WallClockEpoch = val
}

// SetLabels sets the value of Labels.
func (s *FrameMetadata) SetLabels(val []string) {
	s.Labels = val
}

// SetConsensusClient sets the value of ConsensusClient.
func (s *FrameMetadata) SetConsensusClient(val string) {
	s.ConsensusClient = val
}

// SetEventSource sets the value of EventSource.
func (s *FrameMetadata) SetEventSource(val string) {
	s.EventSource = val
}

type GetEthereumNowOK struct {
	Data EthereumNow `json:"data"`
}

// GetData returns the value of Data.
func (s *GetEthereumNowOK) GetData() EthereumNow {
	return s.Data
}

// SetData sets the value of Data.
func (s *GetEthereumNowOK) SetData(val EthereumNow) {
	s.Data = val
}

// GetEthereumNowOKHeaders wraps GetEthereumNowOK with response headers.
type GetEthereumNowOKHeaders struct {
	CacheControl OptString
	Response     GetEthereumNowOK
}

// GetCacheControl returns the value of CacheControl.
func (s *GetEthereumNowOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *GetEthereumNowOKHeaders) GetResponse() GetEthereumNowOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *GetEthereumNowOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *GetEthereumNowOKHeaders) SetResponse(val GetEthereumNowOK) {
	s.Response = val
}

func (*GetEthereumNowOKHeaders) getEthereumNowRes() {}

type GetEthereumSpecOK struct {
	Data EthereumSpecResult `json:"data"`
}

// GetData returns the value of Data.
func (s *GetEthereumSpecOK) GetData() EthereumSpecResult {
	return s.Data
}

// SetData sets the value of Data.
func (s *GetEthereumSpecOK) SetData(val EthereumSpecResult) {
	s.Data = val
}

// GetEthereumSpecOKHeaders wraps GetEthereumSpecOK with response headers.
type GetEthereumSpecOKHeaders struct {
	CacheControl OptString
	Response     GetEthereumSpecOK
}

// GetCacheControl returns the value of CacheControl.
func (s *GetEthereumSpecOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *GetEthereumSpecOKHeaders) GetResponse() GetEthereumSpecOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *GetEthereumSpecOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *GetEthereumSpecOKHeaders) SetResponse(val GetEthereumSpecOK) {
	s.Response = val
}

func (*GetEthereumSpecOKHeaders) getEthereumSpecRes() {}

type GetFrameOK struct {
	Data GetFrameOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *GetFrameOK) GetData() GetFrameOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *GetFrameOK) SetData(val GetFrameOKData) {
	s.Data = val
}

type GetFrameOKData struct {
	Frame Frame `json:"frame"`
}

// GetFrame returns the value of Frame.
func (s *GetFrameOKData) GetFrame() Frame {
	return s.Frame
}

// SetFrame sets the value of Frame.
func (s *GetFrameOKData) SetFrame(val Frame) {
	s.Frame = val
}

// GetFrameOKHeaders wraps GetFrameOK with response headers.
type GetFrameOKHeaders struct {
	CacheControl OptString
	Response     GetFrameOK
}

// GetCacheControl returns the value of CacheControl.
func (s *GetFrameOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *GetFrameOKHeaders) GetResponse() GetFrameOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *GetFrameOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *GetFrameOKHeaders) SetResponse(val GetFrameOK) {
	s.Response = val
}

func (*GetFrameOKHeaders) getFrameRes() {}

type ListMetadataEpochsOK struct {
	Data ListMetadataEpochsOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *ListMetadataEpochsOK) GetData() ListMetadataEpochsOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ListMetadataEpochsOK) SetData(val ListMetadataEpochsOKData) {
	s.Data = val
}

type ListMetadataEpochsOKData struct {
	Epochs     []Epoch            `json:"epochs"`
	Pagination PaginationResponse `json:"pagination"`
}

// GetEpochs returns the value of Epochs.
func (s *ListMetadataEpochsOKData) GetEpochs() []Epoch {
	return s.Epochs
}

// GetPagination returns the value of Pagination.
func (s *ListMetadataEpochsOKData) GetPagination() PaginationResponse {
	return s.Pagination
}

// SetEpochs sets the value of Epochs.
func (s *ListMetadataEpochsOKData) SetEpochs(val []Epoch) {
	s.Epochs = val
}

// SetPagination sets the value of Pagination.
func (s *ListMetadataEpochsOKData) SetPagination(val PaginationResponse) {
	s.Pagination = val
}

// ListMetadataEpochsOKHeaders wraps ListMetadataEpochsOK with response headers.
type ListMetadataEpochsOKHeaders struct {
	CacheControl OptString
	Response     ListMetadataEpochsOK
}

// GetCacheControl returns the value of CacheControl.
func (s *ListMetadataEpochsOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *ListMetadataEpochsOKHeaders) GetResponse() ListMetadataEpochsOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *ListMetadataEpochsOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *ListMetadataEpochsOKHeaders) SetResponse(val ListMetadataEpochsOK) {
	s.Response = val
}

func (*ListMetadataEpochsOKHeaders) listMetadataEpochsRes() {}

type ListMetadataLabelsOK struct {
	Data ListMetadataLabelsOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *ListMetadataLabelsOK) GetData() ListMetadataLabelsOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ListMetadataLabelsOK) SetData(val ListMetadataLabelsOKData) {
	s.Data = val
}

type ListMetadataLabelsOKData struct {
	Labels     []string           `json:"labels"`
	Pagination PaginationResponse `json:"pagination"`
}

// GetLabels returns the value of Labels.
func (s *ListMetadataLabelsOKData) GetLabels() []string {
	return s.Labels
}

// GetPagination returns the value of Pagination.
func (s *ListMetadataLabelsOKData) GetPagination() PaginationResponse {
	return s.Pagination
}

// SetLabels sets the value of Labels.
func (s *ListMetadataLabelsOKData) SetLabels(val []string) {
	s.Labels = val
}

// SetPagination sets the value of Pagination.
func (s *ListMetadataLabelsOKData) SetPagination(val PaginationResponse) {
	s.Pagination = val
}

// ListMetadataLabelsOKHeaders wraps ListMetadataLabelsOK with response headers.
type ListMetadataLabelsOKHeaders struct {
	CacheControl OptString
	Response     ListMetadataLabelsOK
}

// GetCacheControl returns the value of CacheControl.
func (s *ListMetadataLabelsOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *ListMetadataLabelsOKHeaders) GetResponse() ListMetadataLabelsOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *ListMetadataLabelsOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *ListMetadataLabelsOKHeaders) SetResponse(val ListMetadataLabelsOK) {
	s.Response = val
}

func (*ListMetadataLabelsOKHeaders) listMetadataLabelsRes() {}

type ListMetadataNodesOK struct {
	Data ListMetadataNodesOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *ListMetadataNodesOK) GetData() ListMetadataNodesOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ListMetadataNodesOK) SetData(val ListMetadataNodesOKData) {
	s.Data = val
}

type ListMetadataNodesOKData struct {
	Nodes      []string           `json:"nodes"`
	Pagination PaginationResponse `json:"pagination"`
}

// GetNodes returns the value of Nodes.
func (s *ListMetadataNodesOKData) GetNodes() []string {
	return s.Nodes
}

// GetPagination returns the value of Pagination.
func (s *ListMetadataNodesOKData) GetPagination() PaginationResponse {
	return s.Pagination
}

// SetNodes sets the value of Nodes.
func (s *ListMetadataNodesOKData) SetNodes(val []string) {
	s.Nodes = val
}

// SetPagination sets the value of Pagination.
func (s *ListMetadataNodesOKData) SetPagination(val PaginationResponse) {
	s.Pagination = val
}

// ListMetadataNodesOKHeaders wraps ListMetadataNodesOK with response headers.
type ListMetadataNodesOKHeaders struct {
	CacheControl OptString
	Response     ListMetadataNodesOK
}

// GetCacheControl returns the value of CacheControl.
func (s *ListMetadataNodesOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *ListMetadataNodesOKHeaders) GetResponse() ListMetadataNodesOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *ListMetadataNodesOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *ListMetadataNodesOKHeaders) SetResponse(val ListMetadataNodesOK) {
	s.Response = val
}

func (*ListMetadataNodesOKHeaders) listMetadataNodesRes() {}

type ListMetadataOK struct {
	Data ListMetadataOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *ListMetadataOK) GetData() ListMetadataOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ListMetadataOK) SetData(val ListMetadataOKData) {
	s.Data = val
}

func (*ListMetadataOK) listMetadataRes() {}

type ListMetadataOKData struct {
	Frames     []FrameMetadata    `json:"frames"`
	Pagination PaginationResponse `json:"pagination"`
}

// GetFrames returns the value of Frames.
func (s *ListMetadataOKData) GetFrames() []FrameMetadata {
	return s.Frames
}

// GetPagination returns the value of Pagination.
func (s *ListMetadataOKData) GetPagination() PaginationResponse {
	return s.Pagination
}

// SetFrames sets the value of Frames.
func (s *ListMetadataOKData) SetFrames(val []FrameMetadata) {
	s.Frames = val
}

// SetPagination sets the value of Pagination.
func (s *ListMetadataOKData) SetPagination(val PaginationResponse) {
	s.Pagination = val
}

type ListMetadataSlotsOK struct {
	Data ListMetadataSlotsOKData `json:"data"`
}

// GetData returns the value of Data.
func (s *ListMetadataSlotsOK) GetData() ListMetadataSlotsOKData {
	return s.Data
}

// SetData sets the value of Data.
func (s *ListMetadataSlotsOK) SetData(val ListMetadataSlotsOKData) {
	s.Data = val
}

type ListMetadataSlotsOKData struct {
	Slots      []Slot             `json:"slots"`
	Pagination PaginationResponse `json:"pagination"`
}

// GetSlots returns the value of Slots.
func (s *ListMetadataSlotsOKData) GetSlots() []Slot {
	return s.Slots
}

// GetPagination returns the value of Pagination.
func (s *ListMetadataSlotsOKData) GetPagination() PaginationResponse {
	return s.Pagination
}

// SetSlots sets the value of Slots.
func (s *ListMetadataSlotsOKData) SetSlots(val []Slot) {
	s.Slots = val
}

// SetPagination sets the value of Pagination.
func (s *ListMetadataSlotsOKData) SetPagination(val PaginationResponse) {
	s.Pagination = val
}

// ListMetadataSlotsOKHeaders wraps ListMetadataSlotsOK with response headers.
type ListMetadataSlotsOKHeaders struct {
	CacheControl OptString
	Response     ListMetadataSlotsOK
}

// GetCacheControl returns the value of CacheControl.
func (s *ListMetadataSlotsOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetResponse returns the value of Response.
func (s *ListMetadataSlotsOKHeaders) GetResponse() ListMetadataSlotsOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *ListMetadataSlotsOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetResponse sets the value of Response.
func (s *ListMetadataSlotsOKHeaders) SetResponse(val ListMetadataSlotsOK) {
	s.Response = val
}

func (*ListMetadataSlotsOKHeaders) listMetadataSlotsRes() {}

// Ref: #/components/schemas/MetadataQuery
type MetadataQuery struct {
	Filter     OptFrameFilter      `json:"filter"`
	Pagination OptPaginationCursor `json:"pagination"`
}

// GetFilter returns the value of Filter.
func (s *MetadataQuery) GetFilter() OptFrameFilter {
	return s.Filter
}

// GetPagination returns the value of Pagination.
func (s *MetadataQuery) GetPagination() OptPaginationCursor {
	return s.Pagination
}

// SetFilter sets the value of Filter.
func (s *MetadataQuery) SetFilter(val OptFrameFilter) {
	s.Filter = val
}

// SetPagination sets the value of Pagination.
func (s *MetadataQuery) SetPagination(val OptPaginationCursor) {
	s.Pagination = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEpoch returns new OptEpoch with value set to v.
func NewOptEpoch(v Epoch) OptEpoch {
	return OptEpoch{
		Value: v,
		Set:   true,
	}
}

// OptEpoch is optional Epoch.
type OptEpoch struct {
	Value Epoch
	Set   bool
}

// IsSet returns true if OptEpoch was set.
func (o OptEpoch) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEpoch) Reset() {
	var v Epoch
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEpoch) SetTo(v Epoch) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEpoch) Get() (v Epoch, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEpoch) Or(d Epoch) Epoch {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEpochString returns new OptEpochString with value set to v.
func NewOptEpochString(v EpochString) OptEpochString {
	return OptEpochString{
		Value: v,
		Set:   true,
	}
}

// OptEpochString is optional EpochString.
type OptEpochString struct {
	Value EpochString
	Set   bool
}

// IsSet returns true if OptEpochString was set.
func (o OptEpochString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEpochString) Reset() {
	var v EpochString
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEpochString) SetTo(v EpochString) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEpochString) Get() (v EpochString, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEpochString) Or(d EpochString) EpochString {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptForkChoiceExtraData returns new OptForkChoiceExtraData with value set to v.
func NewOptForkChoiceExtraData(v ForkChoiceExtraData) OptForkChoiceExtraData {
	return OptForkChoiceExtraData{
		Value: v,
		Set:   true,
	}
}

// OptForkChoiceExtraData is optional ForkChoiceExtraData.
type OptForkChoiceExtraData struct {
	Value ForkChoiceExtraData
	Set   bool
}

// IsSet returns true if OptForkChoiceExtraData was set.
func (o OptForkChoiceExtraData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptForkChoiceExtraData) Reset() {
	var v ForkChoiceExtraData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptForkChoiceExtraData) SetTo(v ForkChoiceExtraData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptForkChoiceExtraData) Get() (v ForkChoiceExtraData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptForkChoiceExtraData) Or(d ForkChoiceExtraData) ForkChoiceExtraData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptForkChoiceNodeExtraData returns new OptForkChoiceNodeExtraData with value set to v.
func NewOptForkChoiceNodeExtraData(v ForkChoiceNodeExtraData) OptForkChoiceNodeExtraData {
	return OptForkChoiceNodeExtraData{
		Value: v,
		Set:   true,
	}
}

// OptForkChoiceNodeExtraData is optional ForkChoiceNodeExtraData.
type OptForkChoiceNodeExtraData struct {
	Value ForkChoiceNodeExtraData
	Set   bool
}

// IsSet returns true if OptForkChoiceNodeExtraData was set.
func (o OptForkChoiceNodeExtraData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptForkChoiceNodeExtraData) Reset() {
	var v ForkChoiceNodeExtraData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptForkChoiceNodeExtraData) SetTo(v ForkChoiceNodeExtraData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptForkChoiceNodeExtraData) Get() (v ForkChoiceNodeExtraData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptForkChoiceNodeExtraData) Or(d ForkChoiceNodeExtraData) ForkChoiceNodeExtraData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFrameFilter returns new OptFrameFilter with value set to v.
func NewOptFrameFilter(v FrameFilter) OptFrameFilter {
	return OptFrameFilter{
		Value: v,
		Set:   true,
	}
}

// OptFrameFilter is optional FrameFilter.
type OptFrameFilter struct {
	Value FrameFilter
	Set   bool
}

// IsSet returns true if OptFrameFilter was set.
func (o OptFrameFilter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFrameFilter) Reset() {
	var v FrameFilter
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFrameFilter) SetTo(v FrameFilter) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFrameFilter) Get() (v FrameFilter, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFrameFilter) Or(d FrameFilter) FrameFilter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaginationCursor returns new OptPaginationCursor with value set to v.
func NewOptPaginationCursor(v PaginationCursor) OptPaginationCursor {
	return OptPaginationCursor{
		Value: v,
		Set:   true,
	}
}

// OptPaginationCursor is optional PaginationCursor.
type OptPaginationCursor struct {
	Value PaginationCursor
	Set   bool
}

// IsSet returns true if OptPaginationCursor was set.
func (o OptPaginationCursor) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaginationCursor) Reset() {
	var v PaginationCursor
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaginationCursor) SetTo(v PaginationCursor) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaginationCursor) Get() (v PaginationCursor, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaginationCursor) Or(d PaginationCursor) PaginationCursor {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPayloadStatus returns new OptPayloadStatus with value set to v.
func NewOptPayloadStatus(v PayloadStatus) OptPayloadStatus {
	return OptPayloadStatus{
		Value: v,
		Set:   true,
	}
}

// OptPayloadStatus is optional PayloadStatus.
type OptPayloadStatus struct {
	Value PayloadStatus
	Set   bool
}

// IsSet returns true if OptPayloadStatus was set.
func (o OptPayloadStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPayloadStatus) Reset() {
	var v PayloadStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPayloadStatus) SetTo(v PayloadStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPayloadStatus) Get() (v PayloadStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPayloadStatus) Or(d PayloadStatus) PayloadStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSlot returns new OptSlot with value set to v.
func NewOptSlot(v Slot) OptSlot {
	return OptSlot{
		Value: v,
		Set:   true,
	}
}

// OptSlot is optional Slot.
type OptSlot struct {
	Value Slot
	Set   bool
}

// IsSet returns true if OptSlot was set.
func (o OptSlot) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSlot) Reset() {
	var v Slot
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSlot) SetTo(v Slot) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSlot) Get() (v Slot, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSlot) Or(d Slot) Slot {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Offset-based pagination cursor.
// Ref: #/components/schemas/PaginationCursor
type PaginationCursor struct {
	// The number of items to skip.
	Offset OptInt `json:"offset"`
	// The maximum number of items to return.
	Limit OptInt `json:"limit"`
}

// GetOffset returns the value of Offset.
func (s *PaginationCursor) GetOffset() OptInt {
	return s.Offset
}

// GetLimit returns the value of Limit.
func (s *PaginationCursor) GetLimit() OptInt {
	return s.Limit
}

// SetOffset sets the value of Offset.
func (s *PaginationCursor) SetOffset(val OptInt) {
	s.Offset = val
}

// SetLimit sets the value of Limit.
func (s *PaginationCursor) SetLimit(val OptInt) {
	s.Limit = val
}

// Ref: #/components/schemas/PaginationResponse
type PaginationResponse struct {
	// The total number of matching items.
	Total int64 `json:"total"`
}

// GetTotal returns the value of Total.
func (s *PaginationResponse) GetTotal() int64 {
	return s.Total
}

// SetTotal sets the value of Total.
func (s *PaginationResponse) SetTotal(val int64) {
	s.Total = val
}

// The Gloas payload status of a fork-choice node. A Gloas block has a
// `pending` node, which is the parent of its `empty` node (the block
// without its execution payload) and its `full` node (the block with it).
// Ref: #/components/schemas/PayloadStatus
type PayloadStatus string

const (
	PayloadStatusPending PayloadStatus = "pending"
	PayloadStatusEmpty   PayloadStatus = "empty"
	PayloadStatusFull    PayloadStatus = "full"
)

// AllValues returns all PayloadStatus values.
func (PayloadStatus) AllValues() []PayloadStatus {
	return []PayloadStatus{
		PayloadStatusPending,
		PayloadStatusEmpty,
		PayloadStatusFull,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PayloadStatus) MarshalText() ([]byte, error) {
	switch s {
	case PayloadStatusPending:
		return []byte(s), nil
	case PayloadStatusEmpty:
		return []byte(s), nil
	case PayloadStatusFull:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PayloadStatus) UnmarshalText(data []byte) error {
	switch PayloadStatus(data) {
	case PayloadStatusPending:
		*s = PayloadStatusPending
		return nil
	case PayloadStatusEmpty:
		*s = PayloadStatusEmpty
		return nil
	case PayloadStatusFull:
		*s = PayloadStatusFull
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Root string

type Slot int64

type SlotString string

// UnexpectedErrorStatusCode wraps Error with StatusCode.
type UnexpectedErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *UnexpectedErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *UnexpectedErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UnexpectedErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *UnexpectedErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}
