// Code generated by ogen, DO NOT EDIT.

package rest

// setDefaults set default value of fields.
func (s *PaginationCursor) setDefaults() {
	{
		val := int(0)
		s.Offset.SetTo(val)
	}
	{
		val := int(1000)
		s.Limit.SetTo(val)
	}
}
