// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetEthereumNow implements getEthereumNow operation.
	//
	// Get the current wall-clock slot and epoch.
	//
	// GET /api/v1/ethereum/now
	GetEthereumNow(ctx context.Context) (GetEthereumNowRes, error)
	// GetEthereumSpec implements getEthereumSpec operation.
	//
	// Get the Ethereum network name and spec.
	//
	// GET /api/v1/ethereum/spec
	GetEthereumSpec(ctx context.Context) (GetEthereumSpecRes, error)
	// GetFrame implements getFrame operation.
	//
	// Get a single fork-choice frame by ID.
	//
	// GET /api/v1/frames/{id}
	GetFrame(ctx context.Context, params GetFrameParams) (GetFrameRes, error)
	// ListMetadata implements listMetadata operation.
	//
	// List fork-choice frame metadata.
	//
	// POST /api/v1/metadata
	ListMetadata(ctx context.Context, req *MetadataQuery) (ListMetadataRes, error)
	// ListMetadataEpochs implements listMetadataEpochs operation.
	//
	// List distinct epochs across stored frames.
	//
	// POST /api/v1/metadata/epochs
	ListMetadataEpochs(ctx context.Context, req *MetadataQuery) (ListMetadataEpochsRes, error)
	// ListMetadataLabels implements listMetadataLabels operation.
	//
	// List distinct labels across stored frames.
	//
	// POST /api/v1/metadata/labels
	ListMetadataLabels(ctx context.Context, req *MetadataQuery) (ListMetadataLabelsRes, error)
	// ListMetadataNodes implements listMetadataNodes operation.
	//
	// List distinct nodes across stored frames.
	//
	// POST /api/v1/metadata/nodes
	ListMetadataNodes(ctx context.Context, req *MetadataQuery) (ListMetadataNodesRes, error)
	// ListMetadataSlots implements listMetadataSlots operation.
	//
	// List distinct slots across stored frames.
	//
	// POST /api/v1/metadata/slots
	ListMetadataSlots(ctx context.Context, req *MetadataQuery) (ListMetadataSlotsRes, error)
	// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *UnexpectedErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
