// Code generated by ogen, DO NOT EDIT.
package rest

type GetEthereumNowRes interface {
	getEthereumNowRes()
}

type GetEthereumSpecRes interface {
	getEthereumSpecRes()
}

type GetFrameRes interface {
	getFrameRes()
}

type ListMetadataEpochsRes interface {
	listMetadataEpochsRes()
}

type ListMetadataLabelsRes interface {
	listMetadataLabelsRes()
}

type ListMetadataNodesRes interface {
	listMetadataNodesRes()
}

type ListMetadataRes interface {
	listMetadataRes()
}

type ListMetadataSlotsRes interface {
	listMetadataSlotsRes()
}
