// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetEthereumNow implements getEthereumNow operation.
//
// Get the current wall-clock slot and epoch.
//
// GET /api/v1/ethereum/now
func (UnimplementedHandler) GetEthereumNow(ctx context.Context) (r GetEthereumNowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEthereumSpec implements getEthereumSpec operation.
//
// Get the Ethereum network name and spec.
//
// GET /api/v1/ethereum/spec
func (UnimplementedHandler) GetEthereumSpec(ctx context.Context) (r GetEthereumSpecRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFrame implements getFrame operation.
//
// Get a single fork-choice frame by ID.
//
// GET /api/v1/frames/{id}
func (UnimplementedHandler) GetFrame(ctx context.Context, params GetFrameParams) (r GetFrameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetadata implements listMetadata operation.
//
// List fork-choice frame metadata.
//
// POST /api/v1/metadata
func (UnimplementedHandler) ListMetadata(ctx context.Context, req *MetadataQuery) (r ListMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetadataEpochs implements listMetadataEpochs operation.
//
// List distinct epochs across stored frames.
//
// POST /api/v1/metadata/epochs
func (UnimplementedHandler) ListMetadataEpochs(ctx context.Context, req *MetadataQuery) (r ListMetadataEpochsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetadataLabels implements listMetadataLabels operation.
//
// List distinct labels across stored frames.
//
// POST /api/v1/metadata/labels
func (UnimplementedHandler) ListMetadataLabels(ctx context.Context, req *MetadataQuery) (r ListMetadataLabelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetadataNodes implements listMetadataNodes operation.
//
// List distinct nodes across stored frames.
//
// POST /api/v1/metadata/nodes
func (UnimplementedHandler) ListMetadataNodes(ctx context.Context, req *MetadataQuery) (r ListMetadataNodesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetadataSlots implements listMetadataSlots operation.
//
// List distinct slots across stored frames.
//
// POST /api/v1/metadata/slots
func (UnimplementedHandler) ListMetadataSlots(ctx context.Context, req *MetadataQuery) (r ListMetadataSlotsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *UnexpectedErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *UnexpectedErrorStatusCode) {
	r = new(UnexpectedErrorStatusCode)
	return r
}
