/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ByoRouteImport } from './routes/byo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnapshotFrameIdRouteImport } from './routes/snapshot.$frameId'
import { Route as NodeSplatRouteImport } from './routes/node.$'
import { Route as ByoEventsRouteImport } from './routes/byo_.events'
import { Route as SnapshotFrameIdEventsRouteImport } from './routes/snapshot_.$frameId.events'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ByoRoute = ByoRouteImport.update({
  id: '/byo',
  path: '/byo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotFrameIdRoute = SnapshotFrameIdRouteImport.update({
  id: '/snapshot/$frameId',
  path: '/snapshot/$frameId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeSplatRoute = NodeSplatRouteImport.update({
  id: '/node/$',
  path: '/node/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ByoEventsRoute = ByoEventsRouteImport.update({
  id: '/byo_/events',
  path: '/byo/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotFrameIdEventsRoute = SnapshotFrameIdEventsRouteImport.update({
  id: '/snapshot_/$frameId/events',
  path: '/snapshot/$frameId/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/byo': typeof ByoRoute
  '/events': typeof EventsRoute
  '/byo/events': typeof ByoEventsRoute
  '/node/$': typeof NodeSplatRoute
  '/snapshot/$frameId': typeof SnapshotFrameIdRoute
  '/snapshot/$frameId/events': typeof SnapshotFrameIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/byo': typeof ByoRoute
  '/events': typeof EventsRoute
  '/byo/events': typeof ByoEventsRoute
  '/node/$': typeof NodeSplatRoute
  '/snapshot/$frameId': typeof SnapshotFrameIdRoute
  '/snapshot/$frameId/events': typeof SnapshotFrameIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/byo': typeof ByoRoute
  '/events': typeof EventsRoute
  '/byo_/events': typeof ByoEventsRoute
  '/node/$': typeof NodeSplatRoute
  '/snapshot/$frameId': typeof SnapshotFrameIdRoute
  '/snapshot_/$frameId/events': typeof SnapshotFrameIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/byo'
    | '/events'
    | '/byo/events'
    | '/node/$'
    | '/snapshot/$frameId'
    | '/snapshot/$frameId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/byo'
    | '/events'
    | '/byo/events'
    | '/node/$'
    | '/snapshot/$frameId'
    | '/snapshot/$frameId/events'
  id:
    | '__root__'
    | '/'
    | '/byo'
    | '/events'
    | '/byo_/events'
    | '/node/$'
    | '/snapshot/$frameId'
    | '/snapshot_/$frameId/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ByoRoute: typeof ByoRoute
  EventsRoute: typeof EventsRoute
  ByoEventsRoute: typeof ByoEventsRoute
  NodeSplatRoute: typeof NodeSplatRoute
  SnapshotFrameIdRoute: typeof SnapshotFrameIdRoute
  SnapshotFrameIdEventsRoute: typeof SnapshotFrameIdEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byo': {
      id: '/byo'
      path: '/byo'
      fullPath: '/byo'
      preLoaderRoute: typeof ByoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot/$frameId': {
      id: '/snapshot/$frameId'
      path: '/snapshot/$frameId'
      fullPath: '/snapshot/$frameId'
      preLoaderRoute: typeof SnapshotFrameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$': {
      id: '/node/$'
      path: '/node/$'
      fullPath: '/node/$'
      preLoaderRoute: typeof NodeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byo_/events': {
      id: '/byo_/events'
      path: '/byo/events'
      fullPath: '/byo/events'
      preLoaderRoute: typeof ByoEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot_/$frameId/events': {
      id: '/snapshot_/$frameId/events'
      path: '/snapshot/$frameId/events'
      fullPath: '/snapshot/$frameId/events'
      preLoaderRoute: typeof SnapshotFrameIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ByoRoute: ByoRoute,
  EventsRoute: EventsRoute,
  ByoEventsRoute: ByoEventsRoute,
  NodeSplatRoute: NodeSplatRoute,
  SnapshotFrameIdRoute: SnapshotFrameIdRoute,
  SnapshotFrameIdEventsRoute: SnapshotFrameIdEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
